--about README.md
--commit-template "index: $changelog

[ci skip]"
--ignore "ZP Studio Suite/README.txt"
--ignore "ZP Studio Suite/VideoProcessor_Project_Timecode_Overlay.txt"
--ignore "ZP Studio Suite/RB Voice Track.RTrackTemplate"
--ignore "ZP Studio Suite/SRT Track.RTrackTemplate"
--ignore "ZP Studio Suite/ZP_NVDA_Speech.py"
