local C = dofile("ZP Studio Suite/ZP_cerca.lua")
local failures = 0
local function eq(label, a, b)
  if a ~= b then failures = failures + 1; io.stderr:write("FAIL ", label, ": ", tostring(a), " ~= ", tostring(b), "\n") end
end
local function found(text, query) return C.find(text, query) end

local a,b = found("Hijacking", "hijac"); eq("prefisso case-insensitive", a, 1); eq("fine prefix", b, 5)
eq("non parte nel mezzo", found("hijacking", "ac"), nil)
eq("accento ignorato", found("Perché", "perche"), 1)
eq("maiuscola accentata", found("È", "e"), 1)
eq("minuscola vs maiuscola accentata", found("e", "È"), 1)
eq("lettera accentata nel confine", found("città", "citt"), 1)
eq("inizio interno non trovato", found("città", "itta"), nil)
eq("esatto con punteggiatura", found("hijacking,", '"hijacking"'), 1)
eq("esatto rifiuta plurale", found("hijackings", '"hijacking"'), nil)
eq("frase con ultimo prefisso", found("il hijacking", "il hijac"), 1)
for _, wrapped in ipairs({"l'hijacking", "l’hijacking", "«hijacking»", "‹hijacking›", "“hijacking”", "—hijacking", "…hijacking", "·hijacking", "•hijacking", " hijacking", "　hijacking", "、hijacking"}) do
  local expected = wrapped:find("hijacking", 1, true)
  eq("punteggiatura prima: " .. wrapped, found(wrapped, "hijac"), expected)
  eq("evidenzia parola avvolta: " .. wrapped, C.word_matches(wrapped, "hijac"), true)
end
local s,e = found("Èx Perché", "perche"); eq("offset originale con accentate prima", s, 5); eq("offset finale", e, 11)
eq("query vuota", found("abc", ""), nil)
local crs, cre = found("uno\r\ndopo hijacking", "hijac")
eq("offset CRLF originale", crs, 11); eq("fine offset CRLF", cre, 15)
local rows = {{notes="hijacking hijacked"},{notes="Hijacking"}}
local total,current = C.count(rows, "hijac", rows[1])
eq("conteggio per item, non per parola", total, 2); eq("indice del primo item", current, 1)
total,current = C.count(rows, "hijac", rows[2])
eq("indice secondo item", current, 2)
local found_rows, found_total = C.results({{pos=2,notes="qui c'è hijacking e altro"},{pos=1,notes="prima Perché"}}, "hijac", 1)
eq("numero totale risultati item", found_total, 1); eq("rispetta limite", #found_rows, 1)
eq("offset match risultato", found_rows[1].offset_start, 10)
eq("item risultato", found_rows[1].item.pos, 2)
local accented = string.rep("x", 33) .. "È Perché" .. string.rep("y", 33)
local snippets = C.results({{pos=1,notes=accented}}, "perche")
local snippet = snippets[1].snippet
eq("snippet non taglia UTF-8", snippet:find("È", 1, true) ~= nil, true)
eq("snippet UTF-8 valido", utf8.len(snippet) ~= nil, true)
eq("highlight snippet", snippet:sub(snippets[1].snip_a, snippets[1].snip_b), "Perché")
local limited,limited_total=C.results({{pos=1,notes="hijacking"},{pos=2,notes="hijacked"}},"hijac",1)
eq("limite risultati",#limited,1); eq("totale oltre limite",limited_total,2)
-- Sostituisci: solo parole intere, gli accenti contano (la ricerca invece no)
local replaced,n = C.replace("vedere ved", "ved", "guard", true)
eq("sostituisce solo la parola intera", replaced, "vedere guard"); eq("numero sostituzioni", n, 1)
replaced,n = C.replace("E poi è vero, effetti e È", "è", "é", true)
eq("è non cambia e né effetti", replaced, "E poi é vero, effetti e É"); eq("conteggio accenti", n, 2)
replaced,n = C.replace("Perché", "perche", "causa", false)
eq("senza accento non sostituisce perché", n, 0)
eq("ricerca trova perché anche senza accento", C.find("Perché", "perche"), 1)
eq("in modo replace no prefisso", C.find("effetti", "e", nil, "replace"), nil)
replaced,n = C.replace("Perché", "perché", "causa", false)
eq("maiuscola iniziale", replaced, "Causa")
replaced,n = C.replace("PERCHÉ", "perché", "è vero", false)
eq("tutto maiuscolo, accento", replaced, "È VERO")
local rr, rt = C.results({{pos=0,notes="effetti"},{pos=1,notes="lui è qui"}}, "è", 10, "replace")
eq("elenco Sostituisci: solo parole intere", rt, 1)
replaced,n = C.replace("Ciao ciao", "ciao", "ehi", true)
eq("sostituzione tutte", replaced, "Ehi ehi"); eq("conteggio tutte", n, 2)
replaced,n = C.replace("Perché", "perché", "", false)
eq("sostituzione vuota cancella", replaced, ""); eq("conteggio cancellazione", n, 1)
replaced,n = C.replace("uno Perché", '"perché"', "sì", false)
eq("query esatta replacement", replaced, "uno Sì")
replaced = C.replace("E poi", '"e"', "ed", false)
eq("una sola maiuscola = iniziale", replaced, "Ed poi")
replaced = C.replace("È così", '"è"', "era", false)
eq("È iniziale = iniziale", replaced, "Era così")
local sr = C.results({{pos=0,notes="nell abbazia chiuso in tre casse di legno d'abete che vengono nascoste nei locali della biblioteca."}},"abete")
eq("estratto con parole intorno", sr[1].snippet, "…in tre casse di legno d'abete che vengono nascoste nei…")
if failures > 0 then error(failures .. " test falliti") end
print("TUTTI OK")
